# Generated by Django 5.1.5 on 2025-01-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usermgmt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="new_field",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
