name: Deploy recent code

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Droplet & Git pull & restart Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP}}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          port: 22
          script: |
            cd ~/django-deploy/django-deploy
            source venv/bin/activate
            git pull 
            pip3 install -r requirements.txt
            python3 manage.py migrate

            sudo systemctl daemon-reload
            sudo systemctl restart  gunicorn.service
            sudo nginx -t && sudo systemctl restart nginx
